# Generated by Django 4.2.1 on 2023-06-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("focus", "Focus"),
                            ("team", "Team"),
                            ("conference", "Conference"),
                        ],
                        default="focus",
                        max_length=60,
                        verbose_name="Type",
                    ),
                ),
                ("capacity", models.IntegerField(verbose_name="Capacity")),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
    ]
