# Generated by Django 4.2.1 on 2023-06-06 05:39

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="end",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="start",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 6, 5, 39, 23, 257278, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
