# Generated by Django 4.2.1 on 2023-06-06 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0002_room_end_room_start"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="end",
        ),
        migrations.RemoveField(
            model_name="room",
            name="start",
        ),
        migrations.CreateModel(
            name="RoomBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_bookings",
                        to="room.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Book",
                "verbose_name_plural": "Room Books",
            },
        ),
    ]
