# Generated by Django 4.2.1 on 2023-06-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0003_remove_room_end_remove_room_start_roombooking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
            ],
        ),
    ]
