# Generated by Django 4.2.1 on 2023-06-06 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0004_resident"),
    ]

    operations = [
        migrations.AddField(
            model_name="roombooking",
            name="resident",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_bookings",
                to="room.resident",
            ),
            preserve_default=False,
        ),
    ]
