# Generated by Django 4.2.1 on 2023-06-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0005_roombooking_resident"),
    ]

    operations = [
        migrations.AddField(
            model_name="roombooking",
            name="booked",
            field=models.BooleanField(default=False),
        ),
    ]
