# Generated by Django 4.2.1 on 2023-06-06 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0006_roombooking_booked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roombooking",
            name="resident",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_bookings",
                to="room.resident",
            ),
        ),
    ]
