# Generated by Django 4.2.1 on 2023-06-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0013_remove_roombooking_no_overlapping_bookings_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="roombooking",
            name="no_overlapping_bookings",
        ),
    ]
